"""
Auto Relock v4 — Lock + Monitor
=================================
Loads the best operating point from mode_search/latest.json
(generated by mode_search.py) and locks the laser there.

Maintains lock with v3-style piezo recentering via current nudges.
If lock is lost, relocks at the known-good point.

Usage:
  1. Run mode_search.py first (once, or weekly)
  2. Run this script to lock and monitor:  python auto_relock_v4.py
"""

import time
import sys
import csv
import json
import os
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from collections import deque
from datetime import datetime, timezone

import wlmData
import wlmConst
from toptica.lasersdk.dlcpro.v2_0_3 import DLCpro, NetworkConnection

# ─── Configuration ───
DLL_PATH = "/usr/lib/libwlmData.so"
CHANNEL = 3

TOPTICA_IP = "172.29.13.247"
TOPTICA_PORT = 1998
LASER_NAME = "testbed689"
OUTPUT_FILE = "/home/artiq/LaserRelock/relock_log/relock_log_v4_ch%d_%s.csv" % (
    CHANNEL, datetime.now().strftime("%Y%m%d_%H%M%S")
)

# Operating point source
SEARCH_RESULTS = "/home/artiq/LaserRelock/mode_search/latest.json"

# Target frequency
FREQ_TARGET = 434.829040      # THz
FREQ_WINDOW = 0.000002        # THz — ±2 MHz
FREQ_MIN = FREQ_TARGET - FREQ_WINDOW
FREQ_MAX = FREQ_TARGET + FREQ_WINDOW

# Timing
SETTLE_TIME = 0.2             # s
LOCK_SETTLE = 3.0             # s
DELAY = 0.2                   # s — monitor loop interval

# Lock maintenance (v3-style recentering)
STABLE_READINGS = 5
PIEZO_DEADBAND = 0.1          # V
RECENTER_CURRENT_STEP = 0.01  # mA
RECENTER_INTERVAL = 5         # every N cycles
RECENTER_MAX_CURRENT_OFFSET = 0.5  # mA
RECENTER_MAX_FAILURES = 3
RECENTER_DIRECTION = -1       # +1 or -1: sign of current->piezo coupling

# Safety
MAX_RELOCK_ATTEMPTS = 5


def load_wavemeter():
    try:
        wlmData.LoadDLL(DLL_PATH)
    except:
        sys.exit(f"Error: Couldn't find DLL on path {DLL_PATH}.")
    if wlmData.dll.GetWLMCount(0) == 0:
        sys.exit("Error: No running wlmServer instance found.")
    ver = [wlmData.dll.GetWLMVersion(i) for i in range(4)]
    print(f"WLM Version: [{ver[0]}.{ver[1]}.{ver[2]}.{ver[3]}]")


def get_frequency():
    freq = wlmData.dll.GetFrequencyNum(CHANNEL, 0.0)
    if freq <= 0:
        return None
    return freq


def load_operating_point():
    """Load the best operating point from mode_search results."""
    if not os.path.exists(SEARCH_RESULTS):
        print(f"Error: No search results found at {SEARCH_RESULTS}")
        print(f"Run mode_search.py first to find the optimal operating point.")
        sys.exit(1)

    # Resolve symlink to get actual file
    real_path = os.path.realpath(SEARCH_RESULTS)
    with open(real_path) as f:
        data = json.load(f)

    best = data.get("best")
    if best is None:
        print(f"Error: Search found no valid operating point.")
        print(f"Re-run mode_search.py with different parameters.")
        sys.exit(1)

    search_time = data.get("timestamp", "unknown")
    print(f"Loaded operating point from: {os.path.basename(real_path)}")
    print(f"  Search date: {search_time}")
    print(f"  Current:     {best['current_mA']:.2f} mA")
    print(f"  Piezo:       {best['piezo_V']:.1f} V")
    print(f"  MHF width:   {best['mhf_width_V']:.1f} V "
          f"(piezo {best['mhf_piezo_min_V']:.1f}"
          f"-{best['mhf_piezo_max_V']:.1f} V)")
    print(f"  Frequency:   {best['frequency_THz']:.6f} THz")

    n_candidates = len(data.get("all_candidates", []))
    print(f"  Candidates:  {n_candidates} total")

    return best


def try_lock_at(dlc, target_current, target_piezo):
    """Set current and piezo, verify frequency, engage lock."""
    lock = dlc.laser1.dl.lock
    if lock.lock_enabled.get():
        lock.lock_enabled.set(False)
        time.sleep(0.3)

    print(f"  Setting current={target_current:.2f} mA, piezo={target_piezo:.1f} V")
    dlc.laser1.dl.cc.current_set.set(target_current)
    dlc.laser1.dl.pc.voltage_set.set(target_piezo)
    time.sleep(SETTLE_TIME * 3)

    stable_count = 0
    for _ in range(STABLE_READINGS * 2):
        time.sleep(DELAY)
        freq = get_frequency()
        if freq is not None and FREQ_MIN <= freq <= FREQ_MAX:
            stable_count += 1
            if stable_count >= STABLE_READINGS:
                break
        else:
            stable_count = 0

    if stable_count < STABLE_READINGS:
        freq = get_frequency()
        offset = (freq - FREQ_TARGET) * 1e6 if freq else float('nan')
        print(f"  Could not stabilize. Freq offset: {offset:+.1f} MHz")
        return False

    print(f"  Stable! Engaging lock...")
    lock.lock_enabled.set(True)
    time.sleep(LOCK_SETTLE)

    freq = get_frequency()
    lock_state = lock.state_txt.get()
    if freq is not None and FREQ_MIN <= freq <= FREQ_MAX:
        print(f"  Lock held! Freq: {freq:.6f} THz | Lock: {lock_state}")
        return True
    else:
        offset = (freq - FREQ_TARGET) * 1e6 if freq else float('nan')
        print(f"  Lock failed. Freq offset: {offset:+.1f} MHz | Lock: {lock_state}")
        lock.lock_enabled.set(False)
        return False


def main():
    load_wavemeter()

    # ── Load operating point from last search ──
    op = load_operating_point()
    best_current = op["current_mA"]
    best_piezo = op["piezo_V"]
    mhf_width = op["mhf_width_V"]

    print(f"\nConnecting to {LASER_NAME} at {TOPTICA_IP}...")
    toptica_conn = NetworkConnection(TOPTICA_IP, TOPTICA_PORT)
    dlc = DLCpro(toptica_conn)

    try:
        dlc.open()
        print(f"Connected to {LASER_NAME} (SN: {dlc.serial_number.get()})")

        current_now = dlc.laser1.dl.cc.current_act.get()
        piezo_now = dlc.laser1.dl.pc.voltage_act.get()
        print(f"Current state: {current_now:.2f} mA, {piezo_now:.3f} V")

        # ── Lock at operating point ──
        print(f"\nLocking at current={best_current:.2f} mA, piezo={best_piezo:.1f} V...")
        if not try_lock_at(dlc, best_current, best_piezo):
            for offset in [-0.5, 0.5, -1.0, 1.0, -2.0, 2.0]:
                alt_piezo = best_piezo + offset
                print(f"  Trying nearby piezo={alt_piezo:.1f} V...")
                if try_lock_at(dlc, best_current, alt_piezo):
                    best_piezo = alt_piezo
                    break
            else:
                print("\nFATAL: Could not lock. Try re-running mode_search.py.")
                sys.exit(1)

        initial_piezo = dlc.laser1.dl.pc.voltage_act.get()
        initial_current = dlc.laser1.dl.cc.current_act.get()
        print(f"\nLocked! Piezo target: {initial_piezo:.3f} V")
        print(f"MHF width: {mhf_width:.1f} V — "
              f"piezo can drift +/-{mhf_width/2:.1f} V before mode hop")

        # ── Set up monitoring plot ──
        times = deque()
        freq_offsets = deque()
        piezo_vals = deque()
        current_vals = deque()
        freq_base = None
        piezo_target_line = None

        fig, (ax_freq, ax_piezo, ax_curr) = plt.subplots(
            3, 1, figsize=(14, 9), sharex=True)
        fig.canvas.manager.set_window_title(
            "Auto Relock v4 — Ch%d + %s" % (CHANNEL, LASER_NAME))
        fig.subplots_adjust(left=0.10, right=0.95, top=0.93,
                            bottom=0.06, hspace=0.25)

        freq_line, = ax_freq.plot([], [], 'b-o', markersize=2, linewidth=1)
        ax_freq.set_ylabel("MHz")
        ax_freq.set_title("Channel %d — Real-Time Frequency" % CHANNEL)
        ax_freq.grid(True, alpha=0.3)
        base_label = ax_freq.text(-0.01, 1.02, "", transform=ax_freq.transAxes,
                                  fontsize=10, ha='left', va='bottom',
                                  fontweight='bold')
        freq_band = None

        piezo_line, = ax_piezo.plot([], [], 'm-o', markersize=2, linewidth=1)
        ax_piezo.set_ylabel("Voltage (V)")
        ax_piezo.set_title("Piezo Voltage")
        ax_piezo.grid(True, alpha=0.3)

        curr_line, = ax_curr.plot([], [], 'c-o', markersize=2, linewidth=1)
        ax_curr.set_xlabel("Time (s elapsed)")
        ax_curr.set_ylabel("Current (mA)")
        ax_curr.set_title("Laser Current")
        ax_curr.grid(True, alpha=0.3)

        relock_attempts = 0
        recenter_counter = 0
        recenter_failures = 0
        recenter_enabled = True

        t_start = datetime.now(timezone.utc)

        csvfile = open(OUTPUT_FILE, "w", newline="")
        writer = csv.writer(csvfile)
        writer.writerow(["timestamp_utc", "channel", "frequency_THz", "piezo_V",
                         "current_mA", "temp_C", "freq_offset_MHz", "in_window"])
        log_count = 0
        print(f"Logging to: {OUTPUT_FILE}")
        print(f"\n{'='*60}")
        print(f"MONITORING — Lock maintenance active")
        print(f"{'='*60}\n")

        def update(frame):
            nonlocal relock_attempts, log_count
            nonlocal initial_piezo, initial_current, recenter_counter
            nonlocal recenter_failures, recenter_enabled
            nonlocal best_current, best_piezo
            nonlocal freq_base, freq_band, piezo_target_line

            now = datetime.now(timezone.utc)
            elapsed = (now - t_start).total_seconds()

            freq = get_frequency()
            if freq is None:
                return freq_line, piezo_line, curr_line

            try:
                piezo = dlc.laser1.dl.pc.voltage_act.get()
                current_ma = dlc.laser1.dl.cc.current_act.get()
                temp_c = dlc.laser1.dl.tc.temp_act.get()
            except Exception as e:
                print(f"Toptica read error: {e}")
                return freq_line, piezo_line, curr_line

            freq_offset_mhz = (freq - FREQ_TARGET) * 1e6
            in_window = FREQ_MIN <= freq <= FREQ_MAX
            lock = dlc.laser1.dl.lock
            lock_state = lock.state_txt.get()

            # ── First-time plot setup ──
            if freq_base is None:
                freq_base = int(freq * 10000) / 10000.0
                base_label.set_text("+ %.4f THz" % freq_base)
                lo = (FREQ_MIN - freq_base) * 1e6
                hi = (FREQ_MAX - freq_base) * 1e6
                freq_band = ax_freq.axhspan(lo, hi, color='green', alpha=0.15,
                                            label='Target window')
                ax_freq.legend(loc='upper right', fontsize=8)
                piezo_target_line = ax_piezo.axhline(
                    y=initial_piezo, color='green', linestyle='--',
                    linewidth=1, alpha=0.7,
                    label=f'Piezo target ({initial_piezo:.2f}V)')
                ax_piezo.legend(loc='upper right', fontsize=8)

            # ── CSV ──
            now_str = now.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
            writer.writerow([
                now_str, CHANNEL, f"{freq:.6f}",
                f"{piezo:.4f}", f"{current_ma:.4f}",
                f"{temp_c:.4f}" if temp_c else "",
                f"{freq_offset_mhz:.4f}", int(in_window),
            ])
            csvfile.flush()
            log_count += 1

            print(f"Freq: {freq:.6f} THz ({freq_offset_mhz:+7.2f} MHz) | "
                  f"Piezo: {piezo:.3f} V | Current: {current_ma:.3f} mA | "
                  f"Lock: {lock_state}", end="")

            if not in_window:
                print()
                if relock_attempts < MAX_RELOCK_ATTEMPTS:
                    relock_attempts += 1
                    print(f"\n[RELOCK] Attempt {relock_attempts}/{MAX_RELOCK_ATTEMPTS}")
                    if try_lock_at(dlc, best_current, best_piezo):
                        relock_attempts = 0
                        initial_piezo = dlc.laser1.dl.pc.voltage_act.get()
                        initial_current = dlc.laser1.dl.cc.current_act.get()
                        recenter_failures = 0
                        recenter_enabled = True
                        print(f"  [RECENTER] Piezo target reset: {initial_piezo:.3f} V")
                        if piezo_target_line is not None:
                            piezo_target_line.remove()
                        piezo_target_line = ax_piezo.axhline(
                            y=initial_piezo, color='green', linestyle='--',
                            linewidth=1, alpha=0.7,
                            label=f'Piezo target ({initial_piezo:.2f}V)')
                        ax_piezo.legend(loc='upper right', fontsize=8)
                else:
                    print(f"\n[CRITICAL] {MAX_RELOCK_ATTEMPTS} relock attempts failed.")
                    print(f"Re-run mode_search.py — operating point may have shifted.")
                    relock_attempts = 0
            else:
                relock_attempts = 0

                # ── Piezo recentering ──
                if initial_piezo is not None and lock.lock_enabled.get() and recenter_enabled:
                    recenter_counter += 1
                    piezo_error = piezo - initial_piezo

                    if recenter_counter >= RECENTER_INTERVAL and abs(piezo_error) > PIEZO_DEADBAND:
                        recenter_counter = 0

                        current_offset = abs(current_ma - initial_current)
                        if current_offset >= RECENTER_MAX_CURRENT_OFFSET:
                            print(f" | [RECENTER] SAFETY: current offset "
                                  f"{current_offset:.3f} mA", end="")
                        else:
                            if piezo_error > 0:
                                nudge = RECENTER_DIRECTION * RECENTER_CURRENT_STEP
                            else:
                                nudge = -RECENTER_DIRECTION * RECENTER_CURRENT_STEP

                            new_current = current_ma + nudge
                            dlc.laser1.dl.cc.current_set.set(new_current)
                            print(f" | [RECENTER] piezo {piezo_error:+.3f}V -> "
                                  f"current {current_ma:.3f}->{new_current:.3f} mA",
                                  end="")

                            time.sleep(DELAY)
                            freq_check = get_frequency()
                            if (freq_check is not None and
                                    not (FREQ_MIN <= freq_check <= FREQ_MAX)):
                                dlc.laser1.dl.cc.current_set.set(current_ma)
                                recenter_failures += 1
                                print(f" | REVERTED", end="")
                                if recenter_failures >= RECENTER_MAX_FAILURES:
                                    recenter_enabled = False
                                    print(f" | RECENTERING DISABLED", end="")
                            else:
                                recenter_failures = 0

                print()

            # ── Update plots ──
            offset_plot = (freq - freq_base) * 1e6
            times.append(elapsed)
            freq_offsets.append(offset_plot)
            piezo_vals.append(piezo)
            current_vals.append(current_ma)

            t_list = list(times)
            if len(t_list) > 0:
                freq_line.set_data(t_list, list(freq_offsets))
                ax_freq.relim()
                ax_freq.autoscale_view()

                piezo_line.set_data(t_list, list(piezo_vals))
                ax_piezo.relim()
                ax_piezo.autoscale_view()

                curr_line.set_data(t_list, list(current_vals))
                ax_curr.relim()
                ax_curr.autoscale_view()

            return freq_line, piezo_line, curr_line

        ani = animation.FuncAnimation(fig, update, interval=int(DELAY * 1000),
                                       blit=False, cache_frame_data=False)
        plt.show()

    except KeyboardInterrupt:
        print("\nManually stopped.")
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
    finally:
        try:
            csvfile.close()
            print(f"\n{log_count} readings saved to '{OUTPUT_FILE}'.")
        except:
            pass
        try:
            dlc.close()
        except:
            pass
        print("Exiting...")


if __name__ == "__main__":
    main()
