// ─── Document settings ───────────────────────────────────────────────────────

#set document(
  title: "Optical Frequency Combs: Principles and Operation",
  author: "Anurag Borah",
)

#set page(
  paper: "a4",
  margin: (top: 2.5cm, bottom: 2.5cm, left: 3cm, right: 2.5cm),
  numbering: "1",
  number-align: center,
)

#set text(
  font: "New Computer Modern",
  size: 11pt,
  lang: "en",
  region: "GB",
)

#set par(
  justify: true,
  leading: 0.75em,
  first-line-indent: 1.2em,
)

#set heading(numbering: "1.1.1")

#show heading.where(level: 1): it => {
  v(1.5em)
  text(size: 14pt, weight: "bold")[#it]
  v(0.5em)
}

#show heading.where(level: 2): it => {
  v(1em)
  text(size: 12pt, weight: "bold")[#it]
  v(0.2em)
}

#show heading.where(level: 3): it => {
  v(0.8em)
  text(size: 11pt, weight: "bold")[#it]
  v(0.2em)
}

#show raw.where(block: true): block.with(
  fill: luma(245),
  inset: 10pt,
  radius: 4pt,
  width: 100%,
)

// ─── Title page ──────────────────────────────────────────────────────────────

#page(numbering: none)[
  #v(3cm)
  #align(center)[
    #text(size: 22pt, weight: "bold")[
      Optical Frequency Combs: Principles and Operation
    ]
    #v(1cm)
    #line(length: 80%, stroke: 0.5pt)
    #v(1cm)
    #text(size: 13pt)[Anurag Borah]
    #v(0.4cm)
    #text(size: 11pt, style: "italic")[Alkaline Research Team]
    #v(2cm)
    #text(size: 11pt)[#datetime.today().display("[month repr:long] [year]")]
    #v(2cm)

    #align(left)[
      #text(size: 11pt, weight: "bold")[Abstract] \
      #v(0.3em)
      #text(size: 11pt)[
        An optical frequency comb is a laser source whose spectrum consists of a
        large number of discrete, equally spaced lines spanning a broad optical
        bandwidth. Generated by a mode-locked femtosecond laser, the comb
        provides a direct, phase-coherent link between radio-frequency standards
        and optical frequencies. This document explains the physical origin of the
        comb, the two degrees of freedom that must be stabilised ($f_"ceo"$ and
        $f_"rep"$), the $f$-to-$2f$ self-referencing technique used to detect the
        carrier-envelope offset, and the procedure for phase-locking an external
        continuous-wave laser to a comb tooth via beatnote detection. The
        conditions under which a beatnote lock fails — including the pull-out
        condition for a PLL tracking a rapidly shifting beatnote — are discussed,
        along with digital and hardware strategies for improving lock robustness.
      ]
    ]
  ]
]

// ─── Table of contents ───────────────────────────────────────────────────────

#page(numbering: none)[
  #outline(
    title: [Contents],
    indent: 2em,
    depth: 3,
  )
]

// ─── Main document ───────────────────────────────────────────────────────────

#set page(numbering: "1")
#counter(page).update(1)

= Physical Origin of the Frequency Comb

== Mode-Locked Lasers

A mode-locked laser produces a periodic train of ultrashort optical pulses by
forcing many longitudinal cavity modes to oscillate simultaneously with a fixed
phase relationship. The round-trip time of the cavity is $T_"rep" = 2L / v_g$,
where $L$ is the cavity length and $v_g$ is the group velocity of the pulse
envelope. Each pulse is separated from the next by exactly $T_"rep"$, giving a
pulse repetition frequency

$
f_"rep" = 1 / T_"rep"
$

In practice, $f_"rep"$ lies in the range 100 MHz to 10 GHz depending on the
cavity length. The pulse duration is typically 10–100 fs, making these lasers
extremely broadband: a 30 fs pulse centred at 800 nm has a transform-limited
spectral width of roughly 30 THz.

== From Pulse Train to Frequency Comb

The Fourier transform of a perfectly periodic train of identical pulses is a
*comb* of Dirac delta functions, each separated by $f_"rep"$. Real mode-locked
lasers introduce one additional complication: the group velocity and phase
velocity inside the cavity are not equal due to dispersion. As a result, the
carrier wave of each pulse is slightly phase-shifted relative to the envelope of
the previous pulse by an amount $Delta phi_"ceo"$ per round trip. This
carrier-envelope phase slip accumulates from pulse to pulse and shifts the entire
comb spectrum away from zero by the *carrier-envelope offset frequency*:

$
f_"ceo" = frac(Delta phi_"ceo", 2 pi) dot f_"rep", quad f_"ceo" in [0, f_"rep")
$

The frequency of the $n$-th comb tooth is therefore

$
#rect(inset: 8pt)[
  $f_n = f_"ceo" + n dot f_"rep"$
]
$

where $n$ is a large positive integer — typically $3 times 10^5$ to $10^6$ for
teeth in the visible or near-infrared. Because $f_"rep"$ and $f_"ceo"$ are both
radio frequencies (below 1 GHz), they can be measured directly with fast
electronics and stabilised to an absolute reference with sub-hertz precision.
Every comb tooth is then phase-coherently anchored to that reference, realising
an *optical clockwork* that connects the microwave and optical domains.

#figure(
  table(
    columns: (2fr, 3fr, 2fr),
    stroke: 0.5pt,
    inset: 8pt,
    [*Quantity*], [*Physical meaning*], [*Typical value*],
    [$f_"rep"$], [Pulse repetition rate; tooth spacing], [250 MHz – 1 GHz],
    [$f_"ceo"$], [Carrier-envelope offset; comb shift from zero], [0 – $f_"rep"$],
    [$n$], [Tooth index], [$3 times 10^5$ – $10^6$],
    [$f_n$], [Absolute frequency of the $n$-th tooth], [100 THz – 1 PHz],
  ),
  caption: [The four quantities in the comb equation.],
)

= Stabilisation of the Two Degrees of Freedom

A fully stabilised comb requires two independent servo loops: one to fix
$f_"rep"$ and one to fix $f_"ceo"$. Once both are locked, every tooth $f_n$ is
absolutely determined.

== Stabilisation of $f_"rep"$

A fast photodetector illuminated by the pulse train produces a photocurrent at
$f_"rep"$ and its harmonics $2f_"rep"$, $3f_"rep"$, .... The fundamental tone at
$f_"rep"$ is extracted with a bandpass filter and mixed against a
radio-frequency reference oscillator — typically a GPS-disciplined quartz
oscillator or hydrogen maser — to generate a phase error signal. This error
signal is fed back to the cavity length via a piezoelectric mirror mount or an
intracavity electro-optic modulator. Once the loop is closed, $f_"rep"$ inherits
the long-term absolute accuracy and short-term phase noise of the microwave
reference.

The fractional frequency instability achievable is limited by the quality of the
microwave reference: $< 10^{-13}$ at 1 s for a GPS-disciplined oscillator,
$< 10^{-15}$ at 1 s for a hydrogen maser. Multiplied up to optical frequencies
by the factor $n approx 5 times 10^5$, the absolute frequency uncertainty of a
comb tooth is at the millihertz level — negligible for virtually all optical
spectroscopy applications.

== Detection of $f_"ceo"$: the $f$-to-$2f$ Interferometer

The carrier-envelope offset $f_"ceo"$ cannot be detected by a simple photodetector
because no electronic device can follow optical oscillations directly. Instead,
$f_"ceo"$ is measured through *self-referencing*, which requires the comb to span
a full optical octave (a factor of 2 in frequency). If the comb runs from
$f_"low"$ to $f_"high" = 2 f_"low"$, then two teeth at index $n$ and $2n$ exist:

$
f_n &= f_"ceo" + n dot f_"rep" \
f_{2n} &= f_"ceo" + 2n dot f_"rep"
$

Frequency-doubling $f_n$ in a nonlinear crystal gives $2f_n = 2f_"ceo" + 2n dot f_"rep"$.
Beating this against $f_{2n}$ on a photodetector yields

$
2f_n - f_{2n} = (2f_"ceo" + 2n dot f_"rep") - (f_"ceo" + 2n dot f_"rep") = f_"ceo"
$

The $n$-dependence cancels exactly, leaving a pure radio-frequency signal at
$f_"ceo"$ that is detectable with standard electronics. This is the *$f$-to-$2f$
interferometer*.

In practice, few mode-locked oscillators are natively octave-spanning. The comb
spectrum is first broadened to a full octave using a nonlinear medium — most
commonly a few centimetres of photonic crystal fibre (PCF), which has a
carefully engineered dispersion profile near the comb's centre wavelength. A
dichroic beamsplitter then separates the low- and high-frequency wings; the
low-frequency wing is frequency-doubled and recombined with the high-frequency
wing for heterodyne detection.

== Stabilisation of $f_"ceo"$

The $f_"ceo"$ signal detected by the $f$-to-$2f$ interferometer is mixed against
a reference frequency and the error signal is fed back to the pump power of the
mode-locked oscillator. Changing the pump power modifies the nonlinear phase
inside the gain medium, which shifts $Delta phi_"ceo"$ per round trip and hence
$f_"ceo"$. The bandwidth of this pump-power servo is typically a few kilohertz,
sufficient to suppress low-frequency $f_"ceo"$ fluctuations caused by pump laser
intensity noise.

With both loops closed, the comb equation becomes a phase-coherent equality:
every tooth $f_n$ is an exact multiple-plus-offset of the microwave reference,
with no free parameters.

= Locking a CW Laser to the Comb

== Beatnote Detection

To transfer the comb's frequency accuracy to a continuous-wave (CW) laser at
frequency $f_"laser"$, a small fraction of each beam is combined on a fast
photodetector — the *beatnote detector*. The photocurrent contains a component
at the difference frequency between $f_"laser"$ and the nearest comb tooth $f_n$:

$
f_"beat" = |f_"laser" - f_n| = |f_"laser" - f_"ceo" - n dot f_"rep"|
$

The tooth index $n$ is determined from a coarse frequency measurement of the CW
laser (e.g. a wavemeter) using $n = "round"((f_"laser" - f_"ceo") / f_"rep")$.
The beatnote $f_"beat"$ is a radio-frequency signal in the range
$[0, f_"rep" / 2]$ and appears as a peak on an RF spectrum analyser.

== Phase-Locked Loop Architecture

The beatnote is phase-locked to a stable reference frequency $f_"ref"$ (often a
few tens of megahertz) by an electronic servo loop. The phase error
$phi_"err" = phi_"beat" - phi_"ref"$ drives an actuator on the CW laser — most
commonly:

- *Acousto-optic modulator (AOM):* shifts the laser frequency by $plus.minus$ several
  tens of MHz with a servo bandwidth of several megahertz. Used for fast
  corrections.
- *Electro-optic modulator (EOM):* provides even higher bandwidth
  (tens of MHz) but smaller frequency range.
- *Laser piezo or grating:* provides a large frequency range but slow response
  (bandwidth $<$ 10 kHz). Used for slow drift correction.

A common architecture combines an AOM for fast corrections with a piezo for
slow corrections, paralleling the two-actuator approach used for the 689 nm
laser in the main locking system.

When the beatnote lock is closed and both $f_"rep"$ and $f_"ceo"$ are stabilised,
the CW laser frequency is absolutely determined:

$
#rect(inset: 8pt)[
  $f_"laser" = f_"ceo" + n dot f_"rep" + f_"ref"$
]
$

The uncertainty is set by the uncertainties of $f_"ceo"$, $f_"rep"$, and
$f_"ref"$ added in quadrature — at the $10^{-15}$ fractional level for a
GPS-referenced system.

== Identifying the Correct Tooth

Because the beatnote is symmetric about zero, $f_"beat"$ is the same whether
$f_"laser" = f_n + f_"beat"$ or $f_"laser" = f_n - f_"beat"$. The sign
ambiguity is resolved by slightly changing a known comb parameter (e.g. $f_"rep"$)
and observing which direction $f_"beat"$ shifts. Once the sign is established,
the servo sign is set and the lock is engaged.

= Beatnote Lock Failure Modes

== PLL Pull-Out: the Fundamental Bandwidth Limit

A phase-locked loop can track a frequency-modulated input only up to a maximum
rate of frequency change. For a second-order PLL with natural frequency
$omega_n = 2 pi B$ (where $B$ is the loop bandwidth), the pull-out condition is

$
dot(f)_"beat" > 2 pi B^2
$

If the beatnote shifts faster than this rate, the phase error grows without
bound and the loop loses lock. This is the primary failure mode when the CW
laser or the comb experiences a rapid perturbation. A loop with bandwidth
$B = 1$ MHz can track beatnote slew rates up to roughly
$6 times 10^{12}$ Hz/s; a software-based loop with $B = 1$ kHz can track only
$6 times 10^6$ Hz/s — six orders of magnitude less.

== Common Causes of Rapid Beatnote Shifts

*Acoustic perturbations:* vibrations that couple into the CW laser cavity
(e.g. via the optical table or the fibre coupling to the comb) cause fast
frequency fluctuations. Acoustic isolation and rigid fibre mounts reduce this.

*Fibre phase noise:* if the comb light is delivered to the beatnote detector
via a long optical fibre, acoustic and thermal noise on the fibre add phase
noise to the comb teeth, appearing as a fluctuating $f_"beat"$. Fibre noise
cancellation (sending a reflected beam back and locking the round-trip phase)
eliminates this.

*$f_"ceo"$ or $f_"rep"$ transients:* a glitch in the pump laser or cavity can
momentarily shift $f_"ceo"$ by a large amount, pulling $f_"beat"$ out of the
servo capture range. A robust $f_"ceo"$ loop with sufficient bandwidth prevents
this.

*CW laser mode hops:* a sudden jump in the CW laser frequency by a cavity
free spectral range (several GHz) moves $f_"beat"$ to a completely different
tooth. This is not a PLL failure but a physical frequency discontinuity; the
lock must be re-acquired from scratch.

== Strategies for Improving Lock Robustness

#figure(
  table(
    columns: (2fr, 3fr, 2fr),
    stroke: 0.5pt,
    inset: 8pt,
    [*Strategy*], [*Mechanism*], [*Bandwidth gain*],
    [FPGA-based PLL], [Replaces software loop; reduces round-trip latency to $<$ 1 µs], [$times 10^3$],
    [AOM fast actuator], [High-bandwidth frequency shifter; no mechanical resonances], [Up to $tilde.op$5 MHz],
    [Feedforward of $f_"rep"$, $f_"ceo"$], [Cancels known comb fluctuations before they reach the beatnote servo], [Reduces residual $dot(f)_"beat"$],
    [Fibre noise cancellation], [Locks the fibre path length; removes fibre-induced phase noise], [Removes a noise floor],
    [Acoustic isolation], [Reduces the source of fast perturbations], [Problem-dependent],
    [Wider capture range PLL], [Frequency-to-digital converter detects $f_"beat"$ over $>$ one octave], [Extends re-capture after transients],
  ),
  caption: [Strategies for improving beatnote lock robustness.],
)

*Feedforward* deserves special mention for digital implementations. If the
error signals from the $f_"rep"$ and $f_"ceo"$ stabilisation loops are available
as digital monitor outputs, they encode the instantaneous fluctuations of every
comb tooth. These can be combined and applied as a feedforward correction to the
CW laser actuator, reducing the residual beatnote motion seen by the servo loop.
This relaxes the bandwidth requirement and can be implemented entirely in
software if the comb electronics provide suitable outputs.

= Summary

The frequency comb is characterised by two radio-frequency parameters —
$f_"rep"$ and $f_"ceo"$ — that together specify the position of every tooth in
the optical spectrum via $f_n = f_"ceo" + n dot f_"rep"$. Stabilising both
parameters to a microwave reference transfers its accuracy to every tooth.
A CW laser is locked to the comb by phase-locking the beatnote
$f_"beat" = |f_"laser" - f_n|$ to a reference frequency, yielding an absolutely
known optical frequency $f_"laser" = f_"ceo" + n dot f_"rep" + f_"ref"$.
The primary failure mode is a rapidly shifting beatnote exceeding the PLL
pull-out limit $dot(f)_"beat" = 2 pi B^2$; the remedy is higher servo bandwidth,
faster actuators, or feedforward cancellation of the comb fluctuations.
